name: tactile_ssl
channels:
 - pytorch
 - conda-forge
dependencies:
 - python=3.9
 - pytorch=2.0.*
 - torchvision=0.15.*
 - lightning=2.0.*
 - hydra-core
 - hydra-colorlog
 - wandb
 - matplotlib
 - einops
 - tqdm
 - scipy
 - scikit-learn
 - opencv
 - h5py
 - rich
 - pip
 - pip:
    - rootutils
    - pre-commit
    - ikpy
    - gdown==5.1.0
